const double kSpacing = 4;
const kArabicFont = 'BC Arabic';
const kEnglishFont = 'Open Sans';
const double kHorizontalPadding = 16;
const kToken = 'token';
const kEmailMethod = 'email';
const kGoogleMethod = 'google';
const kLoginMethod = 'login_method';
const kHasBadge = 'has_badge';
